# Dependencies
#markdown:         redcarpet
highlighter:      pygments
gems: [jekyll-paginate, jekyll-sitemap]

# Permalinks
permalink:        /:categories/:title/
#relative_permalinks: true

# Setup
title:            Fate Masters
tagline:          'O Podcast dos Algozes dos Jogadpres'
description:      'Esse é o podcast que vai ensinar você a roubar, trapacear, torturar seus jogadores e com isso criar um jogo memorável!'
url:              http://fatemasters.github.io/
baseurl:          /

author:
  name:           'Fábio Emilio Costa'
  url:            https://twitter.com/hufflepuffbr

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  authors:
    output: true
